shopprojects/cartapp/urls.py
from django.urls import path
from . import views

app_name = 'cartapp'

urlpatterns = [
    path('add_cart/<int:product_id>/',views.add_cart, name= 'add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('cart_remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('delete/<int:product_id>/',views.delete, name='delete'),


]

shopprojects/searchapp/urls.py
from . import views
from django.urls import path

app_name='searchapp'


urlpatterns = [

    path('',views.SearchResult,name='SearchResult'),

]

shopprojects/shopapp/urls.py
from . import views
from django.urls import path

app_name = 'shopapp'

urlpatterns = [

    path('',views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat,name='Product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.prodetail, name='prodetail')
]

shopprojects/shopproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shopapp.urls')),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cartapp.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

shopprojects/cartapp/models.py
from django.db import models
from shopapp. models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    Date_added=models.DateField(auto_now=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['Date_added']

    def __str__(self):
        return '{}' .format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quandity=models.IntegerField()
    active=models.BooleanField(default= True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.Price * self.quandity

    def __str__(self):
        return '{}'.format(self.product)

shopprojects/searchapp/models.py
from django.db import models

# Create your models here.

shopprojects/shopapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='Category',blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'Categories'

    def get_url(self):
        return reverse('shopapp:Product_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    Price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='Product')
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['name']
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shopapp:prodetail', args=[self.category.slug,self.slug])


    def __str__(self):
        return '{}'.format(self.name)

shopprojects/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shopapp .models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quandity < cart_item.product.stock:
            cart_item.quandity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quandity=1,cart=cart)
        cart_item.save()
    return redirect('cartapp:cart_detail')

def cart_detail(request,total=0,counter=0,cart_item=None):
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
        cart_item=CartItem.objects.filter(cart=cart,active=True)
        for i in cart_item:
            total += (i.quandity * i.product.Price)
            counter += i.quandity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html', dict(cart_item=cart_item,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quandity > 1:
        cart_item.quandity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cartapp:cart_detail')

def delete(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cartapp:cart_detail')

shopprojects/searchapp/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q

def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

shopprojects/shopapp/views.py
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from django.shortcuts import render, get_object_or_404
from . models import Category, Product
# Create your views here.

def allProdCat(request,c_slug = None):
    c_page = None
    products_list = None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list =Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list =Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)

    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category': c_page,'products':products})

def prodetail(request,c_slug,product_slug):
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
        return render(request,'product.html',{'product':product})

shopprojects/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'custom.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="d-flex flex-column min-vh-100">
<div class="container">
  {% include 'header.html' %}
  {% include 'navbar.html' %}
  {% block body %}
  {% endblock %}
</div>
  {% include 'footer.html' %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

shopprojects/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    You can add the Product to Cart
{% endblock %}
{% block title %}
   Add to cart
{% endblock %}
{% block body %}
{% if not cart_item %}
<div xmlns="http://www.w3.org/1999/html">
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">
                Your Cart Is Empty
            </h1>
            <br>
            <p class="text-center">
                Please click <a href="{% url 'shopapp:allProdCat' %}">here</a>for continue shopping
            </p>
        </div>
    </div>
    {% else %}
    <div class="text-center">
        <br>
        <h2 class="text-center">
            Your Shopping Cart
        </h2>
        <br>
    </div>
    <div class="row mx_auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_table">
                    <tr>
                        <th colspan="5">
                            Your Items
                        </th>
                    </tr>
                <tbody>
                {% for i in cart_item %}
                <tr>
                    <td>
                        <a href="#"><img src="{{i.product.image.url}}" width="100px" height="100px" alt="" class="float-left rounded custom-image"></a>
                    </td>
                    <td class="text-left">
                        {{i.product.name}}
                    <br>
                    SKU:{{i.product.product_id}}
                    <br>
                    Price: ${{i.product.Price}}
                    <br>
                    QTY: {{i.quandity}} x {{i.product.Price}}
                    </td>
                    <td>
                        Total:  <b>${{i.sub_total}}</b>
                    </td>
                    {% if i.quandity < i.product.stock %}
                    <td>
                        <a href="{% url 'cartapp:add_cart' i.product.id %}" class="custom_a <i class= fa fa-plus-square"></i></a>
                        &nbsp<a href="{% url 'cartapp:cart_remove' i.product.id %}" class="custom_a <i class= fa fa-minus-square"></i></a>
                        &nbsp<a href="{% url 'cartapp:delete' i.product.id %}" class="custom_a <i class= fa fa-trash"></i></a>

                    </td>
                    {% else %}
                        <td>
                        &nbsp;   <a href="{% url 'cartapp:cart_remove' i.product.id %}" class="custom_a <i class= fa fa-minus-square"></i></a>
                            <a href="{% url 'cartapp:delete' i.product.id %}" class="custom_a <i class= fa fa-trash"></i></a>
                        </td>
                    {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="my_table">
                <th class="my_th">
                    <tr>
                        <th>
                            <h3>
                                Check Out
                            </h3>
                        </th>
                    </tr>
                </th>
                <tbody>
                <tr>
                    <td class="text-left">
                        Please review your cart-items before proceeding
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        Your total is: <strong>{{total}}</strong>
                    </td>
                </tr>
                </tbody>
            </table>
            <div>
                <br>
                <a href="{% url 'shopapp:allProdCat' %}" class="btn btn-secondary my_button">Continue</a>
                <a href="{% url 'shopapp:allProdCat' %}" class="btn btn-danger my_button">Payment</a>
            </div>
        </div>
    </div>

{% endif %}
{% endblock %}

shopprojects/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if catergory %}
        {{catergory.description|truncatewords:150}}
    {% else %}
        Welcome To Our Shop
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{title.name}}-Our Collections
    {% else %}
        See Our New Collections
    {% endif %}
{% endblock %}

{% block body %}
    {% if category %}
    <div class="row my_row_class">
        <div class="mx_auto">
            <p>
                <a href="{% url 'shopapp:allProdCat' %}">Product Collections</a>
            </p>
        </div>
    </div>
    {% endif %}
    <div class="mx_auto">
        {% if category %}
        <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" height="50px" width="50px">
    </div>
    <div>
        <h3 class="text-center my_title">{{cateogry.name}}</h3>
        <p class="text-justify">{{category.description}}</p>
    </div>
    {% else %}
    <div>
        <img class="my_image my_image_padding" src="{% static 'img/ban.jpg' %}" alt="banner">
    </div>
    <div>
        <h1>
            <center>
                Our Collections
            </center>

        </h1>
        <p class="text-center">
            It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
        </p>
    </div>
    {% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for i in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{i.get_url}}"><img src="{{i.image.url}}" alt="image.name" height="100px" width="100px"></a>
                <div class="card-body">
                    <h3>{{i.name}}</h3>
                    <p>{{i.Price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <div class="text-right">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

shopprojects/templates/footer.html
<style>
.my_footer{
            position: fixed;
            padding-top:10px;
            bottom: 10px;
            width: 87.3%;
            /* Height of the footer*/
            height: 25px;
            background: black;
}

.my_footer p{
         padding-top:0px;
         font-size:10px;
         color:white;
         padding-bottom:35px;
}

</style>

<div class="container">
  <div class="my_footer">
    <p class="text-center">
     &copy; ABC Tech Private Lmt. All rights Reserved
   </p>
  </div>
</div>

shopprojects/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shopapp:allProdCat' %}"></a> <img src="{% static 'img/logo1.png' %}" alt="logo1" width="50px" height="50px">
    </center>
</header>

shopprojects/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shopapp:allProdCat' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{% url 'shopapp:allProdCat' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         All-Items
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for i in links %}
          <a class="dropdown-item" href="{{i.get_url}}">{{i.name}}</a>
            {% endfor %}
      </li>
        {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link disabled" href="{% url 'cartapp:cart_detail' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i>({{item_count}})</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'searchapp:SearchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>

    </form>
  </div>
</nav>

shopprojects/templates/product.html
{% extends 'base.html' %}
{% load static %}
    {% block metadescription %}
        {{product.description}}
    {% endblock %}
    {% block title %}
        {{product.name}}
    {% endblock %}

{% block body %}
<div class="row my_prod">
    <div class="mx_auto">
        <p>
            <a href="{% url 'shopapp:allProdCat' %}">Home|<a href="{{product.category.get_url}}">{{product.category}}</a>{{product.name}} </a>|
        </p>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 col sm-12 col-md-12 col-lg-6 text-center" style="min-width:18rem;">
            <img src="{{product.image.url}}" alt="{{product.name}}">
        </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <h1 class="my_prod_title">{{product.name}}</h1>
                <p><b>${{product.Price}}</b></p>
                <h3 class="my_title">product Description</h3>
                <p class="text-justify my_prod_text">{{product.description}}</p>
                {% if product.stock <= 0 %}
                <h4 class="text-justify my_prod_text">Out Of Stock</h4>
                {% else %}
                <a class="btn btn-secondary" href="{% url 'cartapp:add_cart' product.id %}"> Add to Cart </a>
                {% endif %}
            </div>
    </div>
</div>
{% endblock %}

shopprojects/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        We have variety of collections
{% endblock %}
{% block title %}
    search
{% endblock %}
{% block body %}
<div>
    <p class="text-center my_search">You have searched for:<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for i in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{i.get_url}}"><img src="{{i.image.url}}" alt="image.name" height="100px" width="100px"></a>
                <div class="card-body">
                    <h3>{{i.name}}</h3>
                    <p>{{i.Price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
            <div class="row mx_auto">
                <p class="text-center my_search"> 0 result found </p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}